import {
  Profile,
  Question,
  Exam,
  ExamSubmission,
  Course,
  SubjectConfig,
  JobCircular,
  PaymentTransaction,
  AppSettings,
  SubscriptionPackage,
} from "../types";

export const initialSubjects: SubjectConfig[] = [
  {
    id: "sub-1",
    name_bn: "আল কুরআন ও তাফসির",
    name_ar: "القرآن الكريم والتفسير",
    icon: "BookOpen",
    question_count: 0,
    is_premium_only: false,
    is_active: true,
    topics: ["সূরা আল বাকারা", "সূরা আলে ইমরান", "তাফসিরে জালালাইন", "উসুলুত তাফসির", "মাক্কি ও মাদানি সূরা"],
    color_accent: "emerald",
    order: 1,
  },
  {
    id: "sub-2",
    name_bn: "হাদিস শরিফ ও উসুলুল হাদিস",
    name_ar: "الحديث الشريف وأصول الحديث",
    icon: "Scroll",
    question_count: 0,
    is_premium_only: false,
    is_active: true,
    topics: ["মিশকাতুল মাসাবিহ", "সহিহ বুখারি", "সিহাহ সিত্তা পরিচিতি", "মুস্তালাহুল হাদিস", "সনদ ও মতন"],
    color_accent: "amber",
    order: 2,
  },
  {
    id: "sub-3",
    name_bn: "ফিকহুল ইসলামী ও ফরায়েজ",
    name_ar: "الفقه الإسلامي والفرائض",
    icon: "Scale",
    question_count: 0,
    is_premium_only: false,
    is_active: true,
    topics: ["হিদায়া", "কুদ্দুরী", "মিরাস বণ্টন ও ফরায়েজ", "উসুলুল ফিকহ", "মুয়ামালাত ও ক্রয়-বিক্রয়"],
    color_accent: "teal",
    order: 3,
  },
  {
    id: "sub-4",
    name_bn: "আরবি ব্যাকরণ (নাহু ও সরফ)",
    name_ar: "النحو والصرف والقواعد",
    icon: "Languages",
    question_count: 0,
    is_premium_only: true,
    is_active: true,
    topics: ["কাফিয়া", "শরহে বেকায়া", "মিজানুস সরফ", "ইরাব ও আমেল", "তালিল ও বাবের কায়দা"],
    color_accent: "indigo",
    order: 4,
  },
  {
    id: "sub-5",
    name_bn: "আরবি সাহিত্য ও তরজমা",
    name_ar: "الأدب العربي والترجمة",
    icon: "Feather",
    question_count: 0,
    is_premium_only: true,
    is_active: true,
    topics: ["মাকামাতে হারিরি", "নাফহাতুল ইয়ামান", "আরবি রচনা ও অনুচ্ছেদ", "আধুনিক আরবি পরিভাষা"],
    color_accent: "purple",
    order: 5,
  },
  {
    id: "sub-6",
    name_bn: "বাংলা সাহিত্য ও ব্যাকরণ",
    name_ar: "اللغة البنغالية والأدب",
    icon: "BookMarked",
    question_count: 0,
    is_premium_only: false,
    is_active: true,
    topics: ["মধ্যযুগ ও চর্যাপদ", "আধুনিক বাংলা সাহিত্যিকগণ", "সন্ধি ও সমাস", "কারক ও বিভক্তি", "বানান শুদ্ধি"],
    color_accent: "rose",
    order: 6,
  },
  {
    id: "sub-7",
    name_bn: "ইংরেজি ব্যাকরণ ও সাহিত্য",
    name_ar: "اللغة الإنجليزية",
    icon: "GraduationCap",
    question_count: 0,
    is_premium_only: false,
    is_active: true,
    topics: ["Right form of verbs", "Preposition & Idioms", "Narration & Voice", "Vocabulary", "Translation"],
    color_accent: "blue",
    order: 7,
  },
  {
    id: "sub-8",
    name_bn: "গণিত ও মানসিক দক্ষতা",
    name_ar: "الرياضيات والذكاء",
    icon: "Calculator",
    question_count: 0,
    is_premium_only: false,
    is_active: true,
    topics: ["পাটিগণিত (শতকরা, লাভ-ক্ষতি)", "বীজগণিতীয় সূত্রাবলি", "জ্যামিতি ও পরিমিতি", "মানসিক দক্ষতা"],
    color_accent: "cyan",
    order: 8,
  },
  {
    id: "sub-9",
    name_bn: "সাধারণ জ্ঞান ও ইসলামিক ইতিহাস",
    name_ar: "المعلومات العامة والتاريخ",
    icon: "Globe",
    question_count: 0,
    is_premium_only: false,
    is_active: true,
    topics: ["বাংলাদেশ বিষয়াবলি", "আন্তর্জাতিক সম্পর্ক", "খেলাফতে রাশেদা ও উমাইয়া-আব্বাসীয় যুগ", "মুঘল ও আধুনিক বিশ্ব"],
    color_accent: "emerald",
    order: 9,
  },
  {
    id: "sub-10",
    name_bn: "আইসিটি ও কম্পিউটার জ্ঞান",
    name_ar: "تكنولوجيا المعلومات والكمبيوتر",
    icon: "Laptop",
    question_count: 0,
    is_premium_only: true,
    is_active: true,
    topics: ["হার্ডওয়্যার ও মেমোরি", "ইন্টারনেট ও সাইবার নিরাপত্তা", "এমএস অফিস", "সংখ্যা পদ্ধতি"],
    color_accent: "violet",
    order: 10,
  },
];

// Production data stores - Clean empty arrays, populated directly from Supabase
export const initialQuestions: Question[] = [];

export const initialExams: Exam[] = [];

export const initialCourses: Course[] = [];

export const initialJobCirculars: JobCircular[] = [];

export const initialPayments: PaymentTransaction[] = [];

export const initialProfiles: Profile[] = [];

export const initialSubmissions: ExamSubmission[] = [];

export const initialSubscriptionPackages: SubscriptionPackage[] = [
  {
    id: "monthly",
    name_bn: "১ মাসের স্পেশাল প্ল্যান",
    name_en: "1 Month Access",
    price: 199,
    original_price: 299,
    duration_days: 30,
    discount_tag: "৩৩% ছাড়",
    perks: [
      "সকল আনলিমিটেড মডেল টেস্ট ও লাইভ পরীক্ষা",
      "মাদ্রাসা শিক্ষক নিবন্ধন (NTRCA) স্পেশাল প্রশ্ন ব্যাংক",
      "আরবি হরকত ভিত্তিক স্মার্ট ব্যাখ্যা ও রেফারেন্স",
      "জাতীয় মেধা তালিকা ও বিস্তারিত র‍্যাঙ্কিং এনালাইসিস",
    ],
    is_active: true,
  },
  {
    id: "quarterly",
    name_bn: "৩ মাসের গোল্ড প্ল্যান",
    name_en: "3 Months Access",
    price: 499,
    original_price: 899,
    duration_days: 90,
    badge: "সবচেয়ে জনপ্রিয়",
    discount_tag: "৪৫% ছাড়",
    is_popular: true,
    perks: [
      "১ মাসের সব সুবিধার সাথে ৩ মাসের ফুল এক্সেস",
      "পিডিএফ লেকচার শিট ও অধ্যায়ভিত্তিক হ্যান্ডনোটস ডাউনলোড",
      "ফলাফল অ্যানালিটিক্স ও দুর্বল বিষয় শনাক্তকরণ",
      "প্রিমিয়াম সাপোর্ট ও স্পেশাল গাইডলাইন",
    ],
    is_active: true,
  },
  {
    id: "yearly",
    name_bn: "১ বছরের ভিআইপি মেম্বারশিপ",
    name_en: "1 Year Full Access",
    price: 1299,
    original_price: 2499,
    duration_days: 365,
    badge: "সেরা সঞ্চয়",
    discount_tag: "৪৮% ছাড়",
    perks: [
      "৩৬৫ দিনের জন্য তামরীন প্ল্যাটফর্মের শতভাগ আনলিমিটেড এক্সেস",
      "সকল নতুন ও লাইভ ব্যাচ কোর্সের সাথে ফ্রি অন্তর্ভুক্তি",
      "স্পেশাল ভাইভা গাইড ও মডেল প্রশ্নপত্র",
      "ব্যক্তিগত মেন্টরিং ও ডাউট ক্লিয়ারিং সাপোর্ট",
    ],
    is_active: true,
  },
];

export const initialAppSettings: AppSettings = {
  app_name: "তামরীন (Tamreen)",
  emergency_notice: {
    enabled: false,
    message: "আসন্ন মাদ্রাসা শিক্ষক নিবন্ধন (NTRCA) লাইভ মেগা মডেল টেস্ট আগামী শুক্রবার অনুষ্ঠিত হবে।",
    type: "exam_alert",
    link: "",
  },
  marquee_ticker: {
    enabled: true,
    text: "🌙 তামরীন সেন্ট্রাল প্ল্যাটফর্মে স্বাগতম • বিশুদ্ধ মাদ্রাসা কারিকুলাম ও শিক্ষক নিবন্ধন পরীক্ষার স্মার্ট প্রস্তুতি!",
    speed: 35,
  },
  home_banners: [],
  subscription_packages: initialSubscriptionPackages,
  helpline: {
    phone: "01800000000",
    whatsapp: "8801800000000",
    telegram: "https://t.me/tamreenapp",
    facebook_group: "https://facebook.com/groups/tamreenapp",
    youtube_channel: "https://youtube.com/@tamreen",
    email: "support@tamreenapp.com",
  },
  routine_pdf_url: "https://example.com/tamreen-exam-routine.pdf",
  arabic_font_size_default: "lg",
  maintenance_mode: false,
  live_exam_broadcast_active: false,
  active_broadcast_exam_id: undefined,
};
