import {
  Profile,
  Question,
  Exam,
  ExamSubmission,
  Course,
  SubjectConfig,
  JobCircular,
  PaymentTransaction,
  AppSettings,
  SubscriptionPackage,
} from "../types";

export const initialSubjects: SubjectConfig[] = [
  {
    id: "sub-1",
    name_bn: "আল কুরআন ও তাফসির",
    name_ar: "القرآن الكريم والتفسير",
    icon: "BookOpen",
    question_count: 2450,
    is_premium_only: false,
    is_active: true,
    topics: ["সূরা আল বাকারা", "সূরা আলে ইমরান", "তাফসিরে জালালাইন", "উসুলুত তাফসির", "মাক্কি ও মাদানি সূরা"],
    color_accent: "emerald",
    order: 1,
  },
  {
    id: "sub-2",
    name_bn: "হাদিস শরিফ ও উসুলুল হাদিস",
    name_ar: "الحديث الشريف وأصول الحديث",
    icon: "Scroll",
    question_count: 3120,
    is_premium_only: false,
    is_active: true,
    topics: ["মিশকাতুল মাসাবিহ", "সহিহ বুখারি", "সিহাহ সিত্তা পরিচিতি", "মুস্তালাহুল হাদিস", "সনদ ও মতন"],
    color_accent: "amber",
    order: 2,
  },
  {
    id: "sub-3",
    name_bn: "ফিকহুল ইসলামী ও ফরায়েজ",
    name_ar: "الفقه الإسلامي والفرائض",
    icon: "Scale",
    question_count: 1980,
    is_premium_only: false,
    is_active: true,
    topics: ["হিদায়া", "কুদ্দুরী", "মিরাস বণ্টন ও ফরায়েজ", "উসুলুল ফিকহ", "মুয়ামালাত ও ক্রয়-বিক্রয়"],
    color_accent: "teal",
    order: 3,
  },
  {
    id: "sub-4",
    name_bn: "আরবি ব্যাকরণ (নাহু ও সরফ)",
    name_ar: "النحو والصرف والقواعد",
    icon: "Languages",
    question_count: 3800,
    is_premium_only: true,
    is_active: true,
    topics: ["কাফিয়া", "শরহে বেকায়া", "মিজানুস সরফ", "ইরাব ও আমেল", "তালিল ও বাবের কায়দা"],
    color_accent: "indigo",
    order: 4,
  },
  {
    id: "sub-5",
    name_bn: "আরবি সাহিত্য ও তরজমা",
    name_ar: "الأدب العربي والترجمة",
    icon: "Feather",
    question_count: 1450,
    is_premium_only: true,
    is_active: true,
    topics: ["মাকামাতে হারিরি", "নাফহাতুল ইয়ামান", "আরবি রচনা ও অনুচ্ছেদ", "আধুনিক আরবি পরিভাষা"],
    color_accent: "purple",
    order: 5,
  },
  {
    id: "sub-6",
    name_bn: "বাংলা সাহিত্য ও ব্যাকরণ",
    name_ar: "اللغة البنغالية والأدب",
    icon: "BookMarked",
    question_count: 2200,
    is_premium_only: false,
    is_active: true,
    topics: ["মধ্যযুগ ও চর্যাপদ", "আধুনিক বাংলা সাহিত্যিকগণ", "সন্ধি ও সমাস", "কারক ও বিভক্তি", "বানান শুদ্ধি"],
    color_accent: "rose",
    order: 6,
  },
  {
    id: "sub-7",
    name_bn: "ইংরেজি ব্যাকরণ ও সাহিত্য",
    name_ar: "اللغة الإنجليزية",
    icon: "GraduationCap",
    question_count: 2600,
    is_premium_only: false,
    is_active: true,
    topics: ["Right form of verbs", "Preposition & Idioms", "Narration & Voice", "Vocabulary", "Translation"],
    color_accent: "blue",
    order: 7,
  },
  {
    id: "sub-8",
    name_bn: "গণিত ও মানসিক দক্ষতা",
    name_ar: "الرياضيات والذكاء",
    icon: "Calculator",
    question_count: 1750,
    is_premium_only: false,
    is_active: true,
    topics: ["পাটিগণিত (শতকরা, লাভ-ক্ষতি)", "বীজগণিতীয় সূত্রাবলি", "জ্যামিতি ও পরিমিতি", "মানসিক দক্ষতা"],
    color_accent: "cyan",
    order: 8,
  },
  {
    id: "sub-9",
    name_bn: "সাধারণ জ্ঞান ও ইসলামিক ইতিহাস",
    name_ar: "المعلومات العامة والتاريخ",
    icon: "Globe",
    question_count: 3400,
    is_premium_only: false,
    is_active: true,
    topics: ["বাংলাদেশ বিষয়াবলি", "আন্তর্জাতিক সম্পর্ক", "খেলাফতে রাশেদা ও উমাইয়া-আব্বাসীয় যুগ", "মুঘল ও আধুনিক বিশ্ব"],
    color_accent: "emerald",
    order: 9,
  },
  {
    id: "sub-10",
    name_bn: "আইসিটি ও কম্পিউটার জ্ঞান",
    name_ar: "تكنولوجيا المعلومات والكمبيوتر",
    icon: "Laptop",
    question_count: 1100,
    is_premium_only: true,
    is_active: true,
    topics: ["হার্ডওয়্যার ও মেমোরি", "ইন্টারনেট ও সাইবার নিরাপত্তা", "এমএস অফিস", "সংখ্যা পদ্ধতি"],
    color_accent: "violet",
    order: 10,
  },
];

export const initialQuestions: Question[] = [
  {
    id: "q-101",
    subject_id: "sub-4",
    subject_name: "আরবি ব্যাকরণ (নাহু ও সরফ)",
    topic: "আমেল ও এরাব",
    question: "‘حُرُوفُ الْمُشَبَّهَةِ بِالْفِعْلِ’ এর আমল (Action) কী?",
    arabic_text: "إِنَّ وَأَخَوَاتُهَا تَنْصِبُ الاسْمَ وَتَرْفَعُ الْخَبَرَ",
    options: [
      "ইসমকে রফা এবং খবরকে নসব দেয়",
      "ইসমকে নসব এবং খবরকে রফা দেয়",
      "উভয়টিকে নসব দেয়",
      "উভয়টিকে রফা দেয়",
    ],
    correct_index: 1,
    explanation: "হরুফে মুশাব্বাহা বিল ফিল (إِنَّ، أَنَّ، كَأَنَّ، لَكِنَّ، لَيْتَ، لَعَلَّ) তাদের ইসমকে নসব (ফাতহা) এবং খবরকে রফা (দম্মা) প্রদান করে।",
    source: "আল কাফিয়া ফি ইলমিন নাহু - ইবনে হাজিব",
    difficulty: "Medium",
    exam_type: "NTRCA",
    tags: ["নাহু", "আমেল", "এনটিআরসিএ"],
    created_at: "2026-08-10T10:00:00Z",
  },
  {
    id: "q-102",
    subject_id: "sub-2",
    subject_name: "হাদিস শরিফ ও উসুলুল হাদিস",
    topic: "মুস্তালাহুল হাদিস",
    question: "যে হাদিসের সনদে রাসুলুল্লাহ (সা.) পর্যন্ত কোনো রাবি বাদ পড়েনি, তাকে কী বলা হয়?",
    arabic_text: "الْحَدِيثُ الْمُتَّصِلُ الْمَرْفُوعُ",
    options: [
      "হাদিসে মুতত্তাসিল (متصل)",
      "হাদিসে মুরসাল (مرسل)",
      "হাদিসে মুনকাতি (منقطع)",
      "হাদিসে মু'দাল (معضل)",
    ],
    correct_index: 0,
    explanation: "যে হাদিসের সনদের শুরু থেকে শেষ পর্যন্ত প্রতিটি রাবি তার পূর্ববর্তী রাবি থেকে সরাসরি শ্রবণ করেছেন কোনো বিচ্ছিন্নতা ছাড়া, তাকে হাদিসে মুত্তাসিল বলা হয়।",
    source: "মুকাদ্দামায়ে ইবনুস সালাহ / নুখবাতুল ফিকার",
    difficulty: "Hard",
    exam_type: "NTRCA",
    tags: ["হাদিস", "সনদ", "ফাজিল"],
    created_at: "2026-08-11T12:30:00Z",
  },
  {
    id: "q-103",
    subject_id: "sub-1",
    subject_name: "আল কুরআন ও তাফসির",
    topic: "মাক্কি ও মাদানি সূরা",
    question: "পবিত্র কুরআনে মোট মাক্কি সূরার সংখ্যা কতটি?",
    arabic_text: "عَدَدُ السُّوَرِ الْمَكِّيَّةِ فِي الْقُرْآنِ الْكَرِيمِ",
    options: ["৮৬টি", "২৮টি", "১১৪টি", "৭২টি"],
    correct_index: 0,
    explanation: "সর্বাধিক বিশুদ্ধ অভিমত অনুযায়ী পবিত্র কুরআনের ১১৪টি সূরার মধ্যে ৮৬টি মাক্কি এবং ২৮টি মাদানি সূরা।",
    source: "আল ইতকান ফি উলূমিল কুরআন - ইমাম সুয়ূতী",
    difficulty: "Easy",
    exam_type: "NTRCA",
    tags: ["কুরআন", "উলুমুল কুরআন", "দাখিল"],
    created_at: "2026-08-12T08:15:00Z",
  },
  {
    id: "q-104",
    subject_id: "sub-3",
    subject_name: "ফিকহুল ইসলামী ও ফরায়েজ",
    topic: "ফরায়েজ ও মিরাস",
    question: "মৃত ব্যক্তির সন্তান বা নাতি-নাতনি থাকলে স্বামী (Husband) সম্পত্তির কত অংশ পাবে?",
    arabic_text: "فَإِنْ كَانَ لَهُنَّ وَلَدٌ فَلَكُمُ الرُّبُعُ مِمَّا تَرَكْنَ",
    options: ["১/২ (অর্ধেক)", "১/৪ (এক চতুর্থাংশ)", "১/৮ (এক অষ্টমাংশ)", "২/৩ (দুই তৃতীয়াংশ)"],
    correct_index: 1,
    explanation: "সূরা নিসার ১২ নং আয়াত অনুযায়ী, স্ত্রীর কোনো সন্তান থাকলে স্বামী মোট সম্পত্তির ১/৪ (এক চতুর্থাংশ) পাবে। আর সন্তান না থাকলে অর্ধেক পাবে।",
    source: "আস-সিরাজী ফিল ফরায়েজ / আল হিদায়া",
    difficulty: "Medium",
    exam_type: "NTRCA",
    tags: ["ফিকহ", "ফরায়েজ", "সূরা নিসা"],
    created_at: "2026-08-13T14:20:00Z",
  },
  {
    id: "q-105",
    subject_id: "sub-4",
    subject_name: "আরবি ব্যাকরণ (নাহু ও সরফ)",
    topic: "সরফ - মিজান ও বাব",
    question: "‘اسْتَغْفَرَ’ (ইস্তাগফারা) ক্রিয়াটি কোন বাবের অন্তর্ভুক্ত?",
    arabic_text: "فِعْلُ (اسْتَغْفَرَ) مِنْ بَابِ الاسْتِفْعَالِ",
    options: ["বাবুল ইফতিয়াল", "বাবুল ইস্তিফ'আল", "বাবুত তাফ'ঈল", "বাবুল মুফা'আলা"],
    correct_index: 1,
    explanation: "‘اسْتَغْفَرَ يَسْتَغْفِرُ اسْتِغْفَارًا’ হলো সুলাসী মাজিদ ফিহ এর ‘ইস্তিফ'আল’ (استفعال) বাবের ওজনে গঠিত, যার মূল অক্ষর হলো غ-ف-ر।",
    source: "মিজানুস সরফ ও মুনশাইব",
    difficulty: "Easy",
    exam_type: "NTRCA",
    tags: ["সরফ", "বাব", "মাদরাসা"],
    created_at: "2026-08-14T09:00:00Z",
  },
  {
    id: "q-106",
    subject_id: "sub-6",
    subject_name: "বাংলা সাহিত্য ও ব্যাকরণ",
    topic: "সমাস",
    question: "‘মুখেভাত’ কোন সমাসের উদাহরণ?",
    options: ["অলুক বহুব্রীহি", "মধ্যপদলোপী কর্মধারয়", "দ্বন্দ্ব সমাস", "তৎপুরুষ সমাস"],
    correct_index: 0,
    explanation: "যে বহুব্রীহি সমাসে পূর্বপদের বিভক্তি লোপ পায় না তাকে অলুক বহুব্রীহি বলে। যেমন: মুখে ভাত দেওয়া হয় যে অনুষ্ঠানে = মুখেভাত।",
    source: "বাংলা ভাষার ব্যাকরণ ও নির্মিতি - নবম-দশম শ্রেণি",
    difficulty: "Medium",
    exam_type: "NTRCA",
    tags: ["বাংলা", "ব্যাকরণ", "সমাস"],
    created_at: "2026-08-14T11:00:00Z",
  },
];

export const initialExams: Exam[] = [
  {
    id: "exam-201",
    title: "১৯তম NTRCA শিক্ষক নিবন্ধন স্পেশাল মেগা মডেল টেস্ট - ০১",
    category: "weekly_model_test",
    subject: "আরবি ভাষা ও ইসলামিক স্টাডিজ (পূর্ণাঙ্গ সিলেবাস)",
    syllabus: "আল কুরআন ও তাফসির, হাদিস শরিফ, ফিকহ, আরবি ব্যাকরণ (নাহু-সরফ), বাংলা ও সাধারণ জ্ঞান",
    duration_minutes: 60,
    total_marks: 100,
    pass_marks: 40,
    negative_marking: 0.25,
    start_time: "2026-08-15T09:00:00Z",
    end_time: "2026-08-17T23:59:00Z",
    result_published: false,
    status: "live",
    questions: initialQuestions,
    participant_count: 4820,
    banner_image: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=800&auto=format&fit=crop&q=60",
    is_featured: true,
    created_at: "2026-08-14T08:00:00Z",
  },
  {
    id: "exam-202",
    title: "দৈনিক লাইভ পরীক্ষা: আরবি ব্যাকরণ (নাহু ও সরফ মাস্টারক্লাস)",
    category: "daily_live",
    subject: "আরবি ব্যাকরণ (নাহু ও সরফ)",
    syllabus: "হরুফে মুশাব্বাহা বিল ফিল, এরাবের প্রকারভেদ ও মিজানুস সরফের ১০টি বাব",
    duration_minutes: 20,
    total_marks: 25,
    pass_marks: 10,
    negative_marking: 0.25,
    start_time: "2026-08-15T14:00:00Z",
    end_time: "2026-08-15T22:00:00Z",
    result_published: false,
    status: "live",
    questions: initialQuestions.slice(0, 4),
    participant_count: 1290,
    is_featured: false,
    created_at: "2026-08-15T05:00:00Z",
  },
  {
    id: "exam-203",
    title: "মাদরাসা প্রভাষক (আরবি ও ইসলাম শিক্ষা) ফ্রি ট্রায়াল টেস্ট",
    category: "free_test",
    subject: "ইসলামিক স্টাডিজ ও ফিকহ",
    syllabus: "আল কুরআন, তাফসির ও ফিকহুল ইসলামী এর মৌলিক প্রশ্নাবলি",
    duration_minutes: 30,
    total_marks: 50,
    pass_marks: 20,
    negative_marking: 0,
    start_time: "2026-08-01T00:00:00Z",
    end_time: "2026-12-31T23:59:00Z",
    result_published: true,
    status: "live",
    questions: initialQuestions,
    participant_count: 18450,
    is_featured: true,
    created_at: "2026-08-01T10:00:00Z",
  },
];

export const initialCourses: Course[] = [
  {
    id: "crs-301",
    title: "১৯তম NTRCA শিক্ষক নিবন্ধন স্পেশাল কম্বাইন্ড ব্যাচ (মাদ্রাসা পর্যায়)",
    subtitle: "প্রভাষক (আরবি/ইসলাম শিক্ষা), সহকারী শিক্ষক (ধর্ম) ও মৌলভি পদের পূর্ণাঙ্গ প্রস্তুতি",
    cover_image: "https://images.unsplash.com/photo-1532012164546-f432f2e3edd3?w=800&auto=format&fit=crop&q=60",
    mentor: "মুফতি মাওলানা ড. মাহমুদুল হাসান",
    mentor_title: "সাবেক শিক্ষক পরীক্ষক, ইসলামিক স্টাডিজ বিভাগ",
    original_price: 3500,
    discount_price: 1499,
    course_tag: "NTRCA Special",
    features: [
      "৮০+ লাইভ ইন্টারেক্টিভ জুম ক্লাস",
      "১০০+ পিডিএফ হ্যান্ডনোট ও শিট",
      "৫০+ স্পেশাল অধ্যায়ভিত্তিক মডেল টেস্ট",
      "২৪/৭ প্রাইভেট ডিসকাশন টেলিগ্রাম গ্রুপ",
      "পরীক্ষার পূর্বরাত পর্যন্ত মক ইন্টারভিউ সেশন",
    ],
    custom_buttons: [
      {
        id: "btn-1",
        label: "রুটিন দেখুন",
        action_type: "pdf_url",
        action_value: "https://example.com/tamreen-routine-batch19.pdf",
        icon_name: "Calendar",
        is_active: true,
        order: 1,
        color: "bg-emerald-600 text-white",
      },
      {
        id: "btn-2",
        label: "ফ্রি ডেমো ক্লাস",
        action_type: "video_url",
        action_value: "https://youtube.com/watch?v=sample-demo-tamreen",
        icon_name: "PlayCircle",
        is_active: true,
        order: 2,
        color: "bg-amber-600 text-white",
      },
      {
        id: "btn-3",
        label: "সিলেবাস ডাউনলোড",
        action_type: "pdf_url",
        action_value: "https://example.com/syllabus-ntrca-madrasah.pdf",
        icon_name: "DownloadCloud",
        is_active: true,
        order: 3,
        color: "bg-slate-700 text-white",
      },
      {
        id: "btn-4",
        label: "ভর্তি হোন (৳১৪৯৯)",
        action_type: "payment_drawer",
        action_value: "plan_ntrca_special",
        icon_name: "CheckCircle2",
        is_active: true,
        order: 4,
        color: "bg-emerald-700 text-white font-bold",
      },
    ],
    chapters: [
      {
        id: "ch-1",
        title: "অধ্যায় ১: কুরআনুল কারিম ও উলুমুল কুরআন প্রস্তুতি",
        lectures_count: 8,
        classes: [
          {
            id: "cls-101",
            title: "ক্লাস ১: মাক্কি ও মাদানি সূরার বৈশিষ্ট্য ও শানে নুজুল",
            duration: "১ ঘন্টা ১৫ মিনিট",
            video_url: "https://youtube.com/watch?v=tamreen-quran-1",
            is_free_preview: true,
          },
          {
            id: "cls-102",
            title: "ক্লাস ২: তাফসিরে জালালাইন ও গুরুত্বপূর্ণ আয়াতসমূহের ইরাব",
            duration: "১ ঘন্টা ৩০ মিনিট",
            video_url: "https://youtube.com/watch?v=tamreen-quran-2",
            is_free_preview: false,
          },
        ],
      },
      {
        id: "ch-2",
        title: "অধ্যায় ২: আরবি ব্যাকরণ (নাহু ও সরফ স্পেশাল শর্টকাট)",
        lectures_count: 12,
        classes: [
          {
            id: "cls-201",
            title: "ক্লাস ১: আমেল ও মামুলের চমৎকার ছক এবং সহজে এরাব চেনার নিয়ম",
            duration: "১ ঘন্টা ২০ মিনিট",
            is_live: true,
            live_time: "আগামীকাল রাত ৯:০০ টা",
          },
        ],
      },
    ],
    routine_url: "https://example.com/tamreen-routine-batch19.pdf",
    syllabus_url: "https://example.com/syllabus-ntrca-madrasah.pdf",
    enrolled_count: 1420,
    is_active: true,
    is_featured: true,
    created_at: "2026-08-05T10:00:00Z",
  },
  {
    id: "crs-302",
    title: "আরবি ভাষা ও নাহু-সরফ ডিপ্লোমা মাস্টারকোর্স",
    subtitle: "কুরআন ও হাদিস সরাসরি অনুধাবনে ব্যাকরণ ও শব্দমূলের বাস্তবভিত্তিক প্রশিক্ষণ",
    cover_image: "https://images.unsplash.com/photo-1519791883288-dc8bd696e667?w=800&auto=format&fit=crop&q=60",
    mentor: "মাওলানা আব্দুল কাইয়ূম আল-আজহারী",
    mentor_title: "গ্র্যাজুয়েট, আল-আজহার বিশ্ববিদ্যালয়, মিশর",
    original_price: 2500,
    discount_price: 999,
    course_tag: "Arabi Bhasha & Nahu",
    features: [
      "৫০টি ব্যাকরণভিত্তিক প্র্যাকটিস ক্লাস",
      "আরবি অনুচ্ছেদ লেখার নিয়ম",
      "কোরআনিক অ্যারাবিক স্পিকিং বেসিকস",
      "লাইভ সলভ সেশন ও কুইজ",
    ],
    custom_buttons: [
      {
        id: "btn-201",
        label: "ডেমো ক্লাস",
        action_type: "video_url",
        action_value: "https://youtube.com/watch?v=demo-arabic",
        icon_name: "PlayCircle",
        is_active: true,
        order: 1,
      },
      {
        id: "btn-202",
        label: "ভর্তি ফি ৳৯৯৯",
        action_type: "payment_drawer",
        action_value: "plan_arabic_master",
        icon_name: "CheckCircle2",
        is_active: true,
        order: 2,
      },
    ],
    chapters: [],
    enrolled_count: 890,
    is_active: true,
    is_featured: false,
    created_at: "2026-08-08T10:00:00Z",
  },
];

export const initialJobCirculars: JobCircular[] = [
  {
    id: "job-401",
    title: "১৯তম শিক্ষক নিবন্ধন পরীক্ষা (NTRCA) সার্কুলার ২০২৬",
    organization: "বেসরকারি শিক্ষক নিবন্ধন ও প্রত্যয়ন কর্তৃপক্ষ (NTRCA)",
    vacancies: "৭০,০০০+ (মাদ্রাসা ও স্কুল-কলেজ)",
    deadline: "২০২৬-০৯-১৫",
    apply_link: "http://ntrca.teletalk.com.bd",
    is_hot: true,
    is_active: true,
    educational_req: "ফাজিল / কামিল / দাওরায়ে হাদিস / অনার্স সমমান",
    details: "মাদ্রাসার সহকারী মৌলভি, প্রভাষক (আরবি/ইসলাম শিক্ষা), সহকারী শিক্ষক (ধর্ম) সহ সকল শূন্য পদে শিক্ষক নিবন্ধনের মেগা বিজ্ঞপ্তি।",
    location: "সারা বাংলাদেশ",
    created_at: "2026-08-10T12:00:00Z",
  },
  {
    id: "job-402",
    title: "মাদ্রাসা শিক্ষা অধিদপ্তর বিভিন্ন পদে নিয়োগ বিজ্ঞপ্তি",
    organization: "মাদ্রাসা শিক্ষা অধিদপ্তর (DME)",
    vacancies: "৪৫০ জন",
    deadline: "২০২৬-০৮-৩০",
    apply_link: "http://dme.teletalk.com.bd",
    is_hot: true,
    is_active: true,
    educational_req: "কামিল / মাস্টার্স / ডিগ্রি পাস",
    details: "অফিস সহকারী, কম্পিউটার অপারেটর, হিসাবরক্ষক ও মাঠ পর্যায়ের কর্মকর্তা নিয়োগ।",
    location: "ঢাকা ও বিভাগীয় কার্যালয়",
    created_at: "2026-08-12T14:00:00Z",
  },
  {
    id: "job-403",
    title: "ইসলামিক ফাউন্ডেশন দারুল আরকাম ইবতেদায়ী মাদ্রাসা শিক্ষক নিয়োগ",
    organization: "ইসলামিক ফাউন্ডেশন বাংলাদেশ",
    vacancies: "১২০০ জন",
    deadline: "২০২৬-০৯-১০",
    apply_link: "http://islamicfoundation.gov.bd",
    is_hot: false,
    is_active: true,
    educational_req: "দাওরায়ে হাদিস / কামিল (হাদিস/তাফসির/ফিকহ)",
    details: "সারাদেশের মসজিদভিত্তিক ও স্বতন্ত্র দারুল আরকাম ইবতেদায়ী মাদ্রাসার জন্য শিক্ষক আবশ্যক।",
    location: "সকল উপজেলা ও জেলা",
    created_at: "2026-08-13T09:00:00Z",
  },
];

export const initialSubscriptionPackages: SubscriptionPackage[] = [
  {
    id: "monthly",
    name_bn: "১ মাসের প্রিমিয়াম মেম্বারশিপ",
    name_en: "Monthly Access Pass",
    price: 199,
    original_price: 299,
    duration_days: 30,
    badge: "জনপ্রিয় ট্রায়াল",
    is_popular: false,
    perks: [
      "সকল প্রশ্ন ব্যাংকের পূর্ণাঙ্গ অ্যাক্সেস",
      "দৈনিক লাইভ মডেল টেস্ট আনলিমিটেড",
      "রিয়েল-টাইম লিডারবোর্ড ও অ্যানালিটিক্স",
      "১০টি স্পেশাল সাবজেক্ট টেস্ট",
    ],
    is_active: true,
  },
  {
    id: "quarterly",
    name_bn: "৩ মাসের গোল্ড মেম্বারশিপ",
    name_en: "3 Months Gold Pass",
    price: 499,
    original_price: 799,
    duration_days: 90,
    badge: "সর্বাধিক বিক্রিত",
    is_popular: true,
    perks: [
      "সকল মাসিক সুবিধার পাশাপাশি:",
      "NTRCA স্পেশাল মেগা টেস্ট সিরিজ",
      "সকল পিডিএফ লেকচার শিট ডাউনলোড",
      "সাবজেক্টওয়াইজ ডিফিকাল্টি অ্যানালাইসিস",
      "উইকলি লাইভ ডাউট সলভ গ্রুপ",
    ],
    is_active: true,
  },
  {
    id: "half_yearly",
    name_bn: "৬ মাসের সুপার সেভার প্যাক",
    name_en: "6 Months Super Saver",
    price: 899,
    original_price: 1499,
    duration_days: 180,
    badge: "৫০% ছাড়",
    is_popular: false,
    perks: [
      "৬ মাসের জন্য সব কিছু আনলিমিটেড",
      "কোর্স ও মক টেস্টে অগ্রাধিকার",
      "বিগত ১০ বছরের প্রশ্ন সমাধান ব্যাংক",
      "পারসোনাল মেন্টরশিপ সাপোর্ট",
    ],
    is_active: true,
  },
  {
    id: "yearly",
    name_bn: "১ বছরের ভিআইপি অল-অ্যাক্সেস",
    name_en: "1 Year VIP All-Access",
    price: 1499,
    original_price: 2999,
    duration_days: 365,
    badge: "বেস্ট ভ্যালু",
    is_popular: false,
    perks: [
      "৩৬৫ দিনের পূর্ণাঙ্গ ফ্রিডম",
      "ভবিষ্যতের সকল নতুন কোর্স ও ফিচার ফ্রি",
      "প্রিন্টেবল এক্সক্লুসিভ বুকলেট পিডিএফ",
      "ভিআইপি সাপোর্ট হেল্পলাইন",
    ],
    is_active: true,
  },
];

export const initialPayments: PaymentTransaction[] = [
  {
    id: "pay-501",
    user_id: "usr-881",
    user_name: "মুহাম্মদ আবু বকর সিদ্দিক",
    user_phone: "01712345678",
    gateway: "bKash",
    trx_id: "BK99X887A1",
    amount: 499,
    plan_id: "quarterly",
    plan_name: "৩ মাসের গোল্ড মেম্বারশিপ",
    status: "pending",
    slip_url: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=60",
    admin_note: "বিকাশ অ্যাপ থেকে টাকা পাঠিয়েছে। TrxID যাচাই চলছে।",
    created_at: "2026-08-15T03:20:00Z",
  },
  {
    id: "pay-502",
    user_id: "usr-882",
    user_name: "হাফেজ তানভীর হোসাইন",
    user_phone: "01898765432",
    gateway: "Nagad",
    trx_id: "NG77K442B9",
    amount: 1499,
    plan_id: "yearly",
    plan_name: "১ বছরের ভিআইপি অল-অ্যাক্সেস",
    status: "pending",
    slip_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=60",
    created_at: "2026-08-15T04:10:00Z",
  },
  {
    id: "pay-503",
    user_id: "usr-883",
    user_name: "আব্দুল্লাহ আল মামুন",
    user_phone: "01655443322",
    gateway: "bKash",
    trx_id: "BK33M112P0",
    amount: 199,
    plan_id: "monthly",
    plan_name: "১ মাসের প্রিমিয়াম মেম্বারশিপ",
    status: "approved",
    admin_note: "TrxID ভেরিফাইড। অ্যাকাউন্ট প্রিমিয়াম এক্টিভেট করা হয়েছে।",
    created_at: "2026-08-14T18:45:00Z",
    approved_at: "2026-08-14T19:00:00Z",
  },
  {
    id: "pay-504",
    user_id: "usr-884",
    user_name: "নূরুল ইসলাম চৌধুরী",
    user_phone: "01911223344",
    gateway: "Rocket",
    trx_id: "RK55P889Q4",
    amount: 899,
    plan_id: "half_yearly",
    plan_name: "৬ মাসের সুপার সেভার প্যাক",
    status: "approved",
    created_at: "2026-08-14T14:10:00Z",
    approved_at: "2026-08-14T14:30:00Z",
  },
  {
    id: "pay-505",
    user_id: "usr-885",
    user_name: "মাহমুদা আক্তার",
    user_phone: "01300112233",
    gateway: "bKash",
    trx_id: "BKINVALID9",
    amount: 499,
    plan_id: "quarterly",
    plan_name: "৩ মাসের গোল্ড মেম্বারশিপ",
    status: "rejected",
    admin_note: "ভুল TrxID দেওয়া হয়েছিল। বিকাশ স্টেটমেন্টে পাওয়া যায়নি।",
    created_at: "2026-08-13T11:00:00Z",
  },
];

export const initialProfiles: Profile[] = [
  {
    id: "usr-881",
    full_name: "মুহাম্মদ আবু বকর সিদ্দিক",
    phone: "01712345678",
    email: "abubakar@tamreen.app",
    role: "student",
    is_premium: false,
    madrasah_name: "দারুল উলুম দেওবন্দ কামিল মাদ্রাসা, ঢাকা",
    district: "ঢাকা",
    created_at: "2026-08-01T10:00:00Z",
  },
  {
    id: "usr-882",
    full_name: "হাফেজ তানভীর হোসাইন",
    phone: "01898765432",
    email: "tanvir@tamreen.app",
    role: "student",
    is_premium: false,
    madrasah_name: "জামিয়া আরাবিয়া ইমদাদুল উলুম ফরিদাবাদ",
    district: "চট্টগ্রাম",
    created_at: "2026-08-02T11:30:00Z",
  },
  {
    id: "usr-883",
    full_name: "আব্দুল্লাহ আল মামুন",
    phone: "01655443322",
    email: "mamun@tamreen.app",
    role: "student",
    is_premium: true,
    subscription_plan: "monthly",
    subscription_expiry: "2026-09-14T19:00:00Z",
    madrasah_name: "সরকারি আলিয়া মাদ্রাসা, সিলেট",
    district: "সিলেট",
    created_at: "2026-08-03T15:20:00Z",
  },
  {
    id: "usr-admin",
    full_name: "সুপার অ্যাডমিন (তামরীন)",
    phone: "01700000000",
    email: "admin@tamreen.app",
    role: "admin",
    is_premium: true,
    subscription_plan: "yearly",
    created_at: "2026-01-01T00:00:00Z",
  },
];

export const initialAppSettings: AppSettings = {
  app_name: "তামরীন (Tamreen)",
  emergency_notice: {
    enabled: true,
    message: "📢 ১৯তম শিক্ষক নিবন্ধন (NTRCA) এর জন্য প্রতিদিন রাত ৯:০০ টায় স্পেশাল মেগা লাইভ টেস্ট অনুষ্ঠিত হচ্ছে! সকলের জন্য উন্মুক্ত।",
    type: "exam_alert",
    link: "exam-201",
  },
  marquee_ticker: {
    enabled: true,
    text: "🌙 তামরীন অ্যাপে স্বাগতম • প্রতিদিন নতুন প্রশ্ন ব্যাংক ও ফ্রি লাইভ মডেল টেস্ট যুক্ত হচ্ছে • ১৯তম NTRCA স্পেশাল ব্যাচে ভর্তি চলছে • হেল্পলাইন: ০১৭৯৯-৮৮৭৭৬৬",
    speed: 30,
  },
  home_banners: [
    {
      id: "bnr-1",
      title: "১৯তম শিক্ষক নিবন্ধন (NTRCA) মেগা প্রস্তুতি",
      subtitle: "মাদ্রাসার প্রভাষক ও শিক্ষক পদের জন্য পূর্ণাঙ্গ কোর্স ও ১০০+ মডেল টেস্ট",
      image_url: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=1200&auto=format&fit=crop&q=80",
      redirect_type: "course",
      redirect_target: "crs-301",
      is_active: true,
      order: 1,
    },
    {
      id: "bnr-2",
      title: "সাপ্তাহিক মেগা মডেল টেস্ট - মেধা তালিকা দেখুন",
      subtitle: "সারাদেশের ৫০০০+ মাদ্রাসা শিক্ষার্থীর সাথে আপনার মেধার মূল্যায়ন করুন",
      image_url: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&auto=format&fit=crop&q=80",
      redirect_type: "exam",
      redirect_target: "exam-201",
      is_active: true,
      order: 2,
    },
    {
      id: "bnr-3",
      title: "প্রিমিয়াম মেম্বারশিপে ৫০% পর্যন্ত ছাড়!",
      subtitle: "বিকাশ/নগদে ফি পরিশোধ করে এক ক্লিকেই প্রিমিয়াম অ্যাক্টিভেট করুন",
      image_url: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1200&auto=format&fit=crop&q=80",
      redirect_type: "subscription",
      redirect_target: "quarterly",
      is_active: true,
      order: 3,
    },
  ],
  subscription_packages: initialSubscriptionPackages,
  helpline: {
    phone: "01799887766",
    whatsapp: "8801799887766",
    telegram: "https://t.me/tamreen_madrasah",
    facebook_group: "https://facebook.com/groups/tamreen.official",
    youtube_channel: "https://youtube.com/@tamreen_official",
    email: "support@tamreen.app",
  },
  routine_pdf_url: "https://example.com/tamreen-master-routine-2026.pdf",
  arabic_font_size_default: "lg",
  maintenance_mode: false,
  live_exam_broadcast_active: true,
  active_broadcast_exam_id: "exam-201",
};

export const initialSubmissions: ExamSubmission[] = [
  {
    id: "subm-1",
    exam_id: "exam-201",
    exam_title: "১৯তম NTRCA শিক্ষক নিবন্ধন স্পেশাল মেগা মডেল টেস্ট - ০১",
    user_id: "usr-883",
    user_name: "আব্দুল্লাহ আল মামুন",
    user_phone: "01655443322",
    madrasah_name: "সরকারি আলিয়া মাদ্রাসা, সিলেট",
    score: 92.5,
    total_marks: 100,
    correct_count: 94,
    wrong_count: 6,
    unanswered_count: 0,
    time_taken_seconds: 2450,
    rank: 1,
    answers: { "q-101": 1, "q-102": 0, "q-103": 0, "q-104": 1, "q-105": 1, "q-106": 0 },
    submitted_at: "2026-08-15T09:45:00Z",
  },
  {
    id: "subm-2",
    exam_id: "exam-201",
    exam_title: "১৯তম NTRCA শিক্ষক নিবন্ধন স্পেশাল মেগা মডেল টেস্ট - ০১",
    user_id: "usr-881",
    user_name: "মুহাম্মদ আবু বকর সিদ্দিক",
    user_phone: "01712345678",
    madrasah_name: "দারুল উলুম দেওবন্দ কামিল মাদ্রাসা, ঢাকা",
    score: 87.75,
    total_marks: 100,
    correct_count: 89,
    wrong_count: 5,
    unanswered_count: 6,
    time_taken_seconds: 2980,
    rank: 2,
    answers: { "q-101": 1, "q-102": 0, "q-103": 0, "q-104": 0, "q-105": 1, "q-106": 0 },
    submitted_at: "2026-08-15T10:15:00Z",
  },
  {
    id: "subm-3",
    exam_id: "exam-201",
    exam_title: "১৯তম NTRCA শিক্ষক নিবন্ধন স্পেশাল মেগা মডেল টেস্ট - ০১",
    user_id: "usr-882",
    user_name: "হাফেজ তানভীর হোসাইন",
    user_phone: "01898765432",
    madrasah_name: "জামিয়া আরাবিয়া ইমদাদুল উলুম ফরিদাবাদ",
    score: 82.0,
    total_marks: 100,
    correct_count: 84,
    wrong_count: 8,
    unanswered_count: 8,
    time_taken_seconds: 3120,
    rank: 3,
    answers: { "q-101": 1, "q-102": 1, "q-103": 0, "q-104": 1, "q-105": 1, "q-106": 1 },
    submitted_at: "2026-08-15T11:00:00Z",
  },
];
